## Example notebook to demonstrate how to use the various implementation of the DataSource interface
including: 
1) YahooFinanceDB
2) YahooFinanceAPI

In [1]:
import pandas as pd
import kutils.data.source

### Hitting YahooFinance API

In [2]:
yf_api = kutils.data.source.YahooFinanceAPI(enable_cache=True)
df = yf_api.load_timeseries(tuple(['^SPX', '0001.HK', '^VIX', '^MOVE', '^990100-USD-STRD']),
                        fld='Close',
                        start=pd.Timestamp(2024,12,31),
                        end=pd.Timestamp(2025, 3, 12))
df.tail(10)

                   ^SPX    0001.HK       ^VIX       ^MOVE  ^990100-USD-STRD
2025-02-27  5861.569824  37.699078  21.129999   96.269997       3767.399902
2025-02-28  5954.500000  37.031834  19.629999  104.459999       3805.300049
2025-03-03  5849.720215  37.317795  22.780001  105.650002       3770.300049
2025-03-04  5778.149902  36.841198  23.510000  108.870003       3724.699951
2025-03-05  5842.629883  44.895737  21.930000  104.320000       3777.600098
2025-03-06  5738.520020  49.137482  24.870001  108.949997       3730.899902
2025-03-07  5770.200195  47.183418  23.370001  104.410004       3740.399902
2025-03-10  5614.560059  47.278736  27.860001  112.500000       3651.500000
2025-03-11  5572.069824  47.612362  26.920000  114.599998       3623.199951
2025-03-12  5599.299805  47.040436  24.230000  104.110001       3643.000000

In [3]:
df = yf_api.load_timeseries(tuple(['ADA-USD']),
                        fld=None,
                        start=pd.Timestamp(2024,12,31),
                        end=pd.Timestamp(2025, 2, 28))
df.tail(5)

TICKER       ADA-USD                                                      \
FIELD           Open      High       Low     Close      Volume Dividends
2025-02-24  0.770040  0.775589  0.680667  0.682202   960897545       0.0
2025-02-25  0.682212  0.693038  0.633811  0.682582  1317817123       0.0
2025-02-26  0.682586  0.693577  0.634982  0.645038   869010894       0.0
2025-02-27  0.645053  0.678109  0.628422  0.645585   683537664       0.0
2025-02-28  0.645581  0.645610  0.582188  0.633051  1102255137       0.0

TICKER
FIELD      Stock Splits
2025-02-24          0.0
2025-02-25          0.0
2025-02-26          0.0
2025-02-27          0.0
2025-02-28          0.0

In [4]:
df = yf_api.load_timeseries(tuple(['NVDA', 'AAPL', 'MSFT']),
                        fld='Close', 
                        start=pd.Timestamp(2024,12,31),
                        end=pd.Timestamp(2025, 1, 10))
df.head()

                  NVDA        AAPL        MSFT
2024-12-31  134.246017  249.059448  417.460602
2025-01-02  138.264709  242.525177  414.568604
2025-01-03  144.422684  242.037811  419.292908
2025-01-06  149.381042  243.668915  423.749786
2025-01-07  140.094086  240.894073  418.322296

In [5]:
yf_api.load_info(tuple(['NVDA', 'AAPL', 'MSFT']))

,NVDA,AAPL,MSFT
address1,2788 San Tomas Expressway,One Apple Park Way,One Microsoft Way
city,Santa Clara,Cupertino,Redmond
state,CA,CA,WA
zip,95051,95014,98052-6399
country,United States,United States,United States
...,...,...,...
regularMarketPrice,184.78,252.7402,399.05
shortName,NVIDIA Corporation,Apple Inc.,Microsoft Corporation
longName,NVIDIA Corporation,Apple Inc.,Microsoft Corporation
displayName,NVIDIA,Apple,Microsoft
trailingPegRatio,1.0897,2.2387,1.2904

### Hitting internally onboarded YahooFinance data

In [6]:
yf_db = kutils.data.source.YahooFinanceDB(enable_cache=False)

df = yf_db.load_timeseries(tuple(['^VIX', '^FTSE', '^MOVE', '^990100-USD-STRD']),
                           fld='Close',
                           start=pd.Timestamp(2024,12,31),
                           end=pd.Timestamp(2025, 4, 20))
df.tail(5)

TICKER            ^FTSE       ^MOVE       ^VIX
DATE
2025-04-11  7964.200195  137.259995  37.560001
2025-04-14  8134.299805  132.460007  30.889999
2025-04-15  8249.099609  122.559998  30.120001
2025-04-16  8275.599609  119.400002  32.639999
2025-04-17  8275.700195  114.639999  29.650000

In [7]:
df = yf_db.load_info(tuple(['^VIX',  '^FTSE', '^MOVE', '^990100-USD-STRD']))
df.loc['longName']

TICKER
^990100-USD-STRD               MSCI WORLD
^FTSE                            FTSE 100
^MOVE               ICE BofAML MOVE Index
^VIX                CBOE Volatility Index
Name: longName, dtype: object

In [8]:
df.tail(5)

TICKER,^990100-USD-STRD,^FTSE,^MOVE,^VIX
FIELD,,,,
region,US,US,US,US
shortName,MSCI WORLD,FTSE 100,ICE BofAML MOVE Index,CBOE Volatility Index
symbol,^990100-USD-STRD,^FTSE,^MOVE,^VIX
typeDisp,Index,Index,Index,Index
underlyingSymbol,NaN,NaN,NaN,NaN